# loader
loader:
  data_path: !join-paths [ !home [], 'test', 'data.h5' ] # paths to my files
  batch_size: 15
  features: &feat 10

other_data_path: !absolute-path [ !join-paths ['.', 'local', 'data.h5' ] ]

logger:
  path: !unique-path './results/' # paths to my files
  file: !path './file.txt'

model:
  name: GCN
  input_size: !sum [ *feat, 1 ]
  hidden_size: 64
  output_size: 3

time: !time-stamp []

jimmy:
  template: !load ./examples/plain_yaml_config.yaml
  dump_config: logger/path # key descriptor of the output
  grid-launcher:
    loader/batch_size: [15]
    optimizer/lr: !log-space [-5, -2, 4]